name: Main Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger-ci:
    name: Trigger CI Workflow
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  trigger-cd:
    name: Trigger CD Workflow
    needs: trigger-ci
    uses: ./.github/workflows/cd.yml
    secrets: inherit
