name: Main Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'microservices/**'
      - 'src/**'
      - 'app/**'
      - '!infrastructure/**'
      - '!terraform/**'
  pull_request:
    branches:
      - main
    paths:
      - 'microservices/**'
      - 'src/**'
      - 'app/**'
      - '!infrastructure/**'
      - '!terraform/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  ENVIRONMENT: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'dev' }}

jobs:
  trigger-ci:
    name: Trigger CI Workflow
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      environment: ${{ env.ENVIRONMENT }}

  trigger-cd:
    name: Trigger CD Workflow
    needs: trigger-ci
    uses: ./.github/workflows/cd.yml
    secrets: inherit
    with:
      environment: ${{ env.ENVIRONMENT }}
