name: Main Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'infrastructure/**'
      - 'terraform/**'
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'infrastructure/**'
      - 'terraform/**'
      - '**.md'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  ENVIRONMENT: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'dev' }}

jobs:
  debug-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Print trigger info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Repository: ${{ github.repository }}"
          echo "Changed files:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} || echo "Could not determine changed files"
  
  trigger-ci:
    name: Trigger CI Workflow
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'dev' }}

  trigger-cd:
    name: Trigger CD Workflow
    needs: trigger-ci
    uses: ./.github/workflows/cd.yml
    secrets: inherit
    with:
      environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'dev' }}
